
soleil_formation:
    resource: "@soleilFormationBundle/Resources/config/routing.yml"
    prefix:   /

soleil_article:
    resource: "@soleilArticleBundle/Resources/config/routing.yml"
    prefix:   /

soleil_contact:
    resource: "@soleilContactBundle/Resources/config/routing.yml"
    prefix:   /

soleil_don:
    resource: "@soleilDonBundle/Resources/config/routing.yml"
    prefix:   /

soleil_agenda:
    resource: "@soleilAgendaBundle/Resources/config/routing.yml"
    prefix:   /agenda

soleilecommerce:
    resource: "@soleilecommerceBundle/Resources/config/routing.yml"
    prefix:   /

soleil_site:
    resource: "@soleilSiteBundle/Resources/config/routing.yml"
    prefix:   /
    
#UTILISATEUR : FOSUser

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#ROUTING JS

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    #routes_to_expose: [ (.*) ]
     
        





